networks:
  cats:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt/'
    depends_on:
      - frontend
    networks:
      - cats

  frontend:
    build:
      context: ./app
    networks:
      - cats