networks:
  cats:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
#      - '/etc/letsencrypt:/etc/letsencrypt/'
      - '/etc/letsencrypt/live/vlad-dev.ru/fullchain.pem:/etc/letsencrypt/live/vlad-dev.ru/fullchain.pem'
      - '/etc/letsencrypt/live/vlad-dev.ru/privkey.pem:/etc/letsencrypt/live/vlad-dev.ru/privkey.pem'

    depends_on:
      - frontend
    networks:
      - cats

  frontend:
    build:
      context: ./app
    networks:
      - cats